<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xml="http://www.w3.org/XML/1998/namespace"
	elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">

	<xsd:element name="config">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="wordDictionary" minOccurs="1" maxOccurs="1">	
					<xsd:complexType>						
						<xsd:sequence>
							<xsd:element name="pdfEnabled" type="xsd:boolean" minOccurs="1" maxOccurs="1"/>
							<xsd:element name="catalogEnabled" type="xsd:boolean" minOccurs="1" maxOccurs="1"/>
						</xsd:sequence>
					</xsd:complexType>				
				</xsd:element>

				<xsd:element name="nameDictionary" minOccurs="1" maxOccurs="1">	
					<xsd:complexType>						
						<xsd:sequence>
							<xsd:element name="catalogEnabled" type="xsd:boolean" minOccurs="1" maxOccurs="1"/>
						</xsd:sequence>
					</xsd:complexType>				
				</xsd:element>

				<xsd:element name="kanjiDictionary" minOccurs="1" maxOccurs="1">	
					<xsd:complexType>						
						<xsd:sequence>
							<xsd:element name="catalogEnabled" type="xsd:boolean" minOccurs="1" maxOccurs="1"/>
						</xsd:sequence>
					</xsd:complexType>				
				</xsd:element>

				<xsd:element name="schedulers" minOccurs="1" maxOccurs="1">	
					<xsd:complexType>						
						<xsd:sequence>
							<xsd:element name="stopAllSchedulers" type="xsd:boolean" minOccurs="1" maxOccurs="1"/>						
						</xsd:sequence>
					</xsd:complexType>				
				</xsd:element>
				
				<xsd:element name="redirects" minOccurs="1" maxOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="redirect" minOccurs="0" maxOccurs="unbounded">
								<xsd:complexType>	
									<xsd:attribute name="from" use="required" />
									<xsd:attribute name="to" use="required" />
								</xsd:complexType>
							</xsd:element>							
						</xsd:sequence>				
					</xsd:complexType>
				</xsd:element>
				
				<xsd:element name="firewall" minOccurs="1" maxOccurs="1">
					<xsd:complexType>						
						<xsd:sequence>
							<xsd:element name="hostBlockList" minOccurs="1" maxOccurs="1">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="hostBlock" minOccurs="0" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
												
													<xsd:element name="blackList" minOccurs="0" maxOccurs="1"/>
													
													<xsd:element name="country" minOccurs="0" maxOccurs="unbounded">
														<xsd:complexType>
															<xsd:simpleContent>
																<xsd:extension base="xsd:string"/>						
															</xsd:simpleContent>																							
														</xsd:complexType>										
													</xsd:element>									

													<xsd:element name="notCountry" minOccurs="0" maxOccurs="unbounded">
														<xsd:complexType>
															<xsd:simpleContent>
																<xsd:extension base="xsd:string"/>						
															</xsd:simpleContent>																							
														</xsd:complexType>										
													</xsd:element>									

													<xsd:element name="asn" minOccurs="0" maxOccurs="unbounded">
														<xsd:complexType>
															<xsd:simpleContent>
																<xsd:extension base="xsd:string"/>					
															</xsd:simpleContent>																							
														</xsd:complexType>										
													</xsd:element>
													
													<xsd:element name="notAsn" minOccurs="0" maxOccurs="unbounded">
														<xsd:complexType>
															<xsd:simpleContent>
																<xsd:extension base="xsd:string"/>					
															</xsd:simpleContent>																							
														</xsd:complexType>										
													</xsd:element>											
													
													<xsd:element name="address" minOccurs="0" maxOccurs="unbounded">
														<xsd:complexType>
															<xsd:simpleContent>
																<xsd:extension base="xsd:string"/>
															</xsd:simpleContent>																							
														</xsd:complexType>										
													</xsd:element>											

													<xsd:element name="notAddress" minOccurs="0" maxOccurs="unbounded">
														<xsd:complexType>
															<xsd:simpleContent>
																<xsd:extension base="xsd:string"/>
															</xsd:simpleContent>																							
														</xsd:complexType>										
													</xsd:element>											
															
													<xsd:element name="fullUrl" minOccurs="0" maxOccurs="unbounded">
														<xsd:complexType>
															<xsd:simpleContent>
																<xsd:extension base="xsd:string"/>
															</xsd:simpleContent>																							
														</xsd:complexType>										
													</xsd:element>

													<xsd:element name="notFullUrl" minOccurs="0" maxOccurs="unbounded">
														<xsd:complexType>
															<xsd:simpleContent>
																<xsd:extension base="xsd:string"/>
															</xsd:simpleContent>																							
														</xsd:complexType>										
													</xsd:element>
													
													<xsd:element name="userAgent" minOccurs="0" maxOccurs="unbounded">
														<xsd:complexType>
															<xsd:simpleContent>
																<xsd:extension base="xsd:string"/>
															</xsd:simpleContent>																							
														</xsd:complexType>										
													</xsd:element>

													<xsd:element name="notUserAgent" minOccurs="0" maxOccurs="unbounded">
														<xsd:complexType>
															<xsd:simpleContent>
																<xsd:extension base="xsd:string"/>
															</xsd:simpleContent>																							
														</xsd:complexType>										
													</xsd:element>
												</xsd:sequence>
																								
												<xsd:attribute name="operation" use="required" type="hostBlockOperation" />
												<xsd:attribute name="sendToLoggerListener" use="required" type="xsd:boolean" />
											</xsd:complexType>
										</xsd:element>									
									</xsd:sequence>								
								</xsd:complexType>
							</xsd:element>						
						</xsd:sequence>
					</xsd:complexType>				
				</xsd:element>
			
				<xsd:element name="message" type="message" minOccurs="1" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:simpleType name="hostBlockOperation">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="info"></xsd:enumeration>
			<xsd:enumeration value="block"></xsd:enumeration>
			<xsd:enumeration value="send_random_data"></xsd:enumeration>
			<xsd:enumeration value="redirect_to_captcha"></xsd:enumeration>
		</xsd:restriction>	
	</xsd:simpleType>
	
	<!--  elementy przeniesione i zmodyfikowane z klas JAXB - Message -->
	  <xsd:complexType name="message">
	    <xsd:sequence>
	      <xsd:element name="androidMessageList" type="androidMessageListWrapper" minOccurs="0"/>
	      <xsd:element name="androidAutocompleteList" type="androidAutocompleteMessageListWrapper" minOccurs="0"/>
	      <xsd:element name="webMessageList" type="webMessageListWrapper" minOccurs="0"/>
	    </xsd:sequence>
	  </xsd:complexType>
	
	  <xsd:complexType name="androidMessageListWrapper">
	    <xsd:sequence>
	      <xsd:element name="androidMessage" minOccurs="0" maxOccurs="unbounded">
			  <xsd:complexType>
			    <xsd:sequence>
			      <xsd:element name="userAgentCondition" type="xsd:string" minOccurs="0"/>
			      <xsd:element name="timestamp" type="xsd:string" minOccurs="0"/>
			      <xsd:element name="message" type="xsd:string" minOccurs="0"/>
			      <xsd:element name="htmlMessage" type="xsd:string" minOccurs="0"/>
			    </xsd:sequence>
			  </xsd:complexType>
	      </xsd:element>
	    </xsd:sequence>
	  </xsd:complexType>
	
	  <xsd:complexType name="androidAutocompleteMessageListWrapper">
	    <xsd:sequence>
	      <xsd:element name="androidAutocompleteMessage" type="androidAutocompleteMessageEntry" minOccurs="0" maxOccurs="unbounded"/>
	    </xsd:sequence>
	  </xsd:complexType>
	
	  <xsd:complexType name="androidAutocompleteMessageEntry">
	        <xsd:sequence>
		      <xsd:element name="userAgentCondition" type="xsd:string" minOccurs="0"/>
		      <xsd:element name="timestamp" type="xsd:string" minOccurs="0"/>
		      <xsd:element name="message" type="xsd:string" minOccurs="0"/>
	          <xsd:element name="autocompleteType" type="xsd:string" minOccurs="0"/>
	        </xsd:sequence>
	  </xsd:complexType>
	
	  <xsd:complexType name="webMessageListWrapper">
	    <xsd:sequence>
	      <xsd:element name="webMessage" minOccurs="0" maxOccurs="unbounded">
			  <xsd:complexType>
			    <xsd:sequence>
			      <xsd:element name="userAgentCondition" type="xsd:string" minOccurs="0"/>
			      <xsd:element name="timestamp" type="xsd:string" minOccurs="0"/>
			      <xsd:element name="htmlMessage" type="xsd:string" minOccurs="0"/>
			    </xsd:sequence>
			  </xsd:complexType>	      
	      </xsd:element>
	    </xsd:sequence>
	  </xsd:complexType>	
</xsd:schema>
